"""empty message

Revision ID: 33a1d121e6fa
Revises: bd99ec15c8bc
Create Date: 2019-04-17 16:44:56.732057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a1d121e6fa'
down_revision = 'bd99ec15c8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_received',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('receive_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.drop_table('msgs')
    op.add_column('user', sa.Column('broadcast_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'broadcast_count')
    op.create_table('msgs',
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], name='msgs_message_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='msgs_user_id_fkey'),
    sa.PrimaryKeyConstraint('message_id', 'user_id', name='msgs_pkey')
    )
    op.drop_table('message_received')
    # ### end Alembic commands ###
