"""empty message

Revision ID: bd99ec15c8bc
Revises: cbde80d9ed3f
Create Date: 2019-04-15 00:08:30.211063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd99ec15c8bc'
down_revision = 'cbde80d9ed3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_active')
    # ### end Alembic commands ###
